web/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin

# Enables the admin:
admin.autodiscover()

urlpatterns = patterns('',
    # link to the resources files
    (r'^resources/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
    
    #mainpage
    (r'^$', 'reviews.views.index'),
    
    #reviews
	(r'^fotobox/$', 'profiles.views.fotobox'),
	(r'^flickr_login/$', 'profiles.views.flickr_login'),
	(r'^editFoto/$', 'profiles.views.editFoto'),
	(r'^panorama_manual/$', 'profiles.views.panorama_manual'),
	(r'^panorama_result/$', 'profiles.views.panorama_callback'),
	(r'^flickr_login_callback/$', 'profiles.views.flickr_login_callback'),
    (r'^reviews/$', 'reviews.views.index'),
    (r'^reviews/recommended$', 'reviews.views.index'),
    (r'^reviews/review/(\d+)', 'reviews.views.review'),
    (r'^save_review/', 'reviews.views.save_review'),
    (r'^create_review/', 'reviews.views.create_review'),
    (r'^reviews/mine/', 'reviews.views.my_reviews'),
	
	#Favorites
    (r'^favorites/', 'reviews.views.list_favorites'),
    (r'^profiles/toggle_favorite', 'profiles.views.toggle_favorite'),
	
    #other pages
    (r'^accounts/', include('registration.urls')),
	(r'^account_info/', 'profiles.views.account_info'),
	(r'^account_update/', 'profiles.views.account_update'),
	(r'^search/', 'reviews.views.search_reviews'),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #Admin Site
    url(r'^admin/', include(admin.site.urls)),
)

web/reviews/models.py
import datetime
from django.db import models

from django.contrib.auth.models import User

class Company(models.Model):
    """(Company description)"""
    name = models.CharField(blank=True, max_length=100)

    def __unicode__(self):
        return "%s" % self.name
    
      
class Division(models.Model):
    """(Division description)"""
    name = models.CharField(blank=True, max_length=100)
    company = models.ForeignKey(Company)
    
    def __unicode__(self):
        return "%s %s" % (self.company, self.name)
    

POSITION_TYPE_CHOICES = (
    ('I', 'Internship'),
    ('P', 'Part-time'),
    ('F', 'Full-time')
)
CLASS_CHOICES = (
    ('FR','Freshman'),
    ('SO','Sophomore'),
    ('JR','Junior'),
    ('SR','Senior'),
    ('GR','Graduate')
)

RANKING_CHOICES = zip( range(1,6), range(1,6) )
class DivisionReview(models.Model):
    """(PositionReview description)"""
    #date_posted = models.DateTimeField(blank=True, default=datetime.datetime.now)
    
    reviewer = models.ForeignKey(User)
    employer = models.ForeignKey(Division)
    position_title = models.CharField(blank=True, max_length=100)
    position_type = models.CharField(choices=POSITION_TYPE_CHOICES, blank=True, max_length=1)

    views = models.IntegerField(default=0)

    year_taken = models.CharField(choices=CLASS_CHOICES,blank=True, max_length=2)
    
    overall = models.IntegerField(choices=RANKING_CHOICES, blank=True, null=True)
    pay = models.IntegerField(choices=RANKING_CHOICES, blank=True, null=True)
    hours = models.IntegerField(choices=RANKING_CHOICES, blank=True, null=True)
    difficulty = models.IntegerField(choices=RANKING_CHOICES, blank=True, null=True)
    
    comment = models.TextField(blank=True)

    def __unicode__(self):
        return "%s:%s" % (self.employer, self.reviewer)

web/templates/base.html
{% load i18n %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<!DOCTYPE html>
<head>
	{% block css %}{% endblock %}
	<link type="text/css" href="/resources/css/base.css" rel="stylesheet" />
	
	<script type="text/javascript" src="/resources/js/jquery-1.5.2.min.js"></script>
	<script type="text/javascript" src="/resources/js/jquery-ui-1.8.12.custom.min.js"></script>
	<script type="text/javascript" src="/resources/js/main.js"></script>
	<script type="text/javascript" src="/resources/js/protovis-d3.2.js"></script>
	{% block js %}{% endblock %}
	
	<title>{% block title %}Jobious{% endblock %}</title>
</head>
<body id="body">
	<div id="topbar_underlay"></div>
	<div id="container" class="center_align">
		<div id="topbar_div" >
			<div id="loginpositioning_div" class="right_float">
				<div id="search_div" class="right_float">
					<form method="post" action="/search/" method="post" class="searchform" id="searchform">
						{% csrf_token %}
						<input id="searchbar" class="text" type="text" name="searchbar" value="">
						<input id="searchbutton" type="submit" value="Search it!" />
					</form>
				</div>			
				<div id="un_div" class="right_float">
					{% if user.is_authenticated %}
							<a href="/account_info/{{ user.username }}" class="topbar_big_link"> {{ user.username }}</a>					
							<a href="{% url auth_logout %}" class="topbar_small_link">{% trans "log out" %}</a>
					{% else %}
						<div id="login_div" class="right_float">
							<a href="{% url auth_login %}" class="topbar_big_link">{% trans "Log In" %}</a>
						</div>
						<div id="or_div" class="right_float">
							or
						</div>
						<div id="reg_div" class="right_float">
							<a href="{% url registration_register %}" class="topbar_big_link">{% trans "Register" %}</a>
						</div>
					{% endif %}
				</div>
			</div>
		</div>

		<div id="nav_div">
			{% block nav %}
			<div id="logo_div" class="left_float">
				<a href="/"><img src="/resources/img/logo.png" id="logoimg" title="Jobious Logo"></a>
			</div>
			<div id="read_navbar" class="navbar left_float">
				{% if user.is_authenticated %}
					<div id="top_button_div" class="nav_button_div left_float">
						<a href="/reviews/recommended" id="nav_button_link_top" class="nav_button_link">Recommended</a>
					</div>
					<div id="favorites_button_div" class="nav_button_div left_float">
						<a href="/favorites" id="nav_button_link_favs" class="nav_button_link">	Favorites</a>
					</div>
					<div id="my_posts_button_div" class="nav_button_div left_float" >
						<a href="/reviews/mine" id="nav_button_link_mine" class="nav_button_link">Mine</a>
					</div>
				{% endif %}
			</div>
			<div id="post_navbar" class="navbar nav_button_div right_float">
				<div id="post_review_button_div" class="nav_button_div">
					<a href="/create_review/" id="nav_button_link_new" class="nav_button_link" alt="add job review">+</a>
				</div>
			</div>
			{% endblock %}
		</div>
		<div id="content_div">
			<div id="content_top">
				<div id="content_description">
					<h1>
						{% block content_description%}
						Top Employers
						{% endblock %}
					</h1>
				</div>
			</div>
			<div id="content">
				{% block content %}
				You should see some content here.
				{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>

web/templates/create_review.html
{% extends "base.html" %}
{% load i18n %}

{% block css %}
<link type="text/css" href="/resources/css/create_review.css" rel="stylesheet" />
{% endblock %}

{% block js %}
<script type="text/javascript" src="/resources/js/create_review.js"></script>
<script type="text/javascript" src="/resources/js/jquery.ui.slider.js"></script>
{% endblock %}

{% block content_description %}
	Create New Review
{% endblock %}

{% block content %}

{% if user.is_authenticated %}

<form id="create_review" action="/save_review/" method="post">
	<div class="left_float" id="left">
	<table>
		{% csrf_token %}
		<tr>
			<td>{% trans "Username" %}: </td>
			<td>{{ user.username }}</td>
		</tr>
		<tr>			
			<td>{% trans "Employer" %}:</td>
			<td><input type="text" name="company" /></td>
		</tr>
		<tr>
			<td>{% trans "Division" %}: </td>
			<td><input type="text" name="division" /></td>
		</tr>
		<tr>
			<td>{% trans "Position Title" %}: </td>
			<td><input type="text" name="position_title" /></td>
		</tr>
		<tr>
			<td>{% trans "Position Type" %}:</td>
			<td>
				<select name="position_type">
					<option value="I">Internship</option>
					<option value="P">Part-Time</option>
					<option value="F">Full-Time</option>
				</select>
			</td>
		</tr>

		<tr>
			<td>{% trans "Year Taken" %}:</td>
			<td>
				<select name="year_taken">
					<option value="FR">Freshman</option>
					<option value="SO">Sophomore</option>
					<option value="JR">Junior</option>
					<option value="SR">Senior</option>
					<option value="GR">Graduate</option>
				</select>
			</td>
		</tr>
		
		<tr>
			<td>{% trans "Overall" %}: </td>
			<td>
				<select name="overall">
					<option>1</option>
					<option>2</option>
					<option>3</option>
					<option>4</option>
					<option>5</option>
				</select>
			</td>
		</tr>
		
		<tr>
			<td>{% trans "Pay" %}: </td>
			<td>
				<select name="pay">
					<option>1</option>
					<option>2</option>
					<option>3</option>
					<option>4</option>
					<option>5</option>
				</select>
			</td>
		</tr>
		
		<tr>
			<td>{% trans "Hours" %}: </td>
			<td>
				<select name="hours">
					<option>1</option>
					<option>2</option>
					<option>3</option>
					<option>4</option>
					<option>5</option>
				</select>
			</td>
		</tr>
		
		<tr>
			<td>{% trans "Difficulty" %}: </td>
			<td>
				<select name="difficulty">
					<option>1</option>
					<option>2</option>
					<option>3</option>
					<option>4</option>
					<option>5</option>
				</select>
			</td>
		</tr>
		</table>
		</div>
		<div class="right_float" id="right">
			{% trans "Comment" %}: 
			<textarea name="comment" ></textarea>
			<div id="submit_div" align="right">	
				<input id="submit_button" type="submit" value="Submit" />
			</div>
		</div>


</form>					
{% else %}
	<a href="{% url auth_login %}">{% trans "Log in" %}</a>
	<a href="{% url registration_register %}">{% trans "Register" %}</a>
{% endif %}

{% endblock %}

web/templates/foto_login.html
<!DOCTYPE html>
<head>
	
	<script type="text/javascript" src="/resources/js/jquery-1.5.2.min.js"></script>
	<script type="text/javascript" src="/resources/js/jquery-ui-1.8.12.custom.min.js"></script>
	<script type="text/javascript" src="/resources/js/foto.js"></script>
	<link type="text/css" href="/resources/css/foto.css" rel="stylesheet" />
	<link type="text/css" href="/resources/css/flick/jquery-ui-1.8.12.custom.css" rel="stylesheet" />
	
	<title>
	{% block title %}
		Login
	{%endblock%}
	</title>
</head>
<body id="body">
<div class="ui-widget-header" style="border:solid 1px;width:100%;" id="login_div"><span class="logo">fotobo</span><span id="logo">x</span></div>
{% block content %}
<div  class="ui-widget-content content_div">
	
	<form action="/flickr_login_callback/">
		<p style="font-family:helvetica">Enter Flickr Username</p>
		<input id="username" style="width:195px" name="username"><br>
		<input style="width:200px" class="btn" type="submit" value="ToolKit">
	</form>
	<form action="/panorama_manual/">
		<input style="width:200px" class="btn" type="submit" value="Manual Panorama">
		<input id="uname" style="display:none;" name="uname">
	</form>
</div>
{%endblock%}
</body>

</html>

web/templates/fotobox.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<!DOCTYPE html>
<head>
	
	<script type="text/javascript" src="/resources/js/jquery-1.5.2.min.js"></script>
	{% block js %}{% endblock %}
	
	<title>Fotobox</title>
</head>
<body id="body">
	<form action="http://127.0.0.1:7000/cgi-bin/seam_carving.exe">
		<p>enter URL</p>
		<INPUT NAME="url" SIZE="100"><BR>
		<p>enter width</p>
		<INPUT NAME="wPercent" SIZE="10"><BR>
		<p>enter height</p>
		<INPUT NAME="hPercent" SIZE="10"><BR>
		<INPUT TYPE="SUBMIT" VALUE="Go!">
	</form>
</body>
</html>

web/templates/fotobox_seam.html
{% extends "foto_login.html" %}


{% block title %}
	Seam Carving
{% endblock %}

{%block content%}
	<div class="content_div" id="pix">
		<div><img src={{url}}></div>
	<form action="http://127.0.0.1:7000/cgi-bin/seam_carving.exe">
		<INPUT style="display:none" NAME="url" value={{url}} SIZE="10"><BR>
		<INPUT style="display:none" NAME="username" value={{username}}>
		<p class="hel">Enter Desired Width</p>
		<INPUT NAME="wPercent" SIZE="10"><BR>
		<p class="hel">Enter Desired Height</p>
		<INPUT NAME="hPercent" SIZE="10"><BR>
		<INPUT TYPE="SUBMIT" class="btn" VALUE="Go!">
	</form>
	</div>
{%endblock%}

web/templates/fotobox_spanish.html
{%extends "foto_login.html"%}
{%block content %}
	<div class="content_div">
	<div><img src={{url}}></div>
	<form action="http://127.0.0.1:7000/cgi-bin/spanish_castle_web.exe">
		<INPUT style="display:none" NAME="url" value={{url}} SIZE="10"><BR>
		<INPUT style="display:none" NAME="username" value={{username}}>
		<INPUT class="btn" TYPE="SUBMIT" VALUE="Generate Illusion!">
	</form>
	</div>
{% endblock %}
</html>

web/templates/index.html
{% extends "base.html" %}
{% load i18n %}

web/templates/median_demosaic.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<!DOCTYPE html>
<head>
	
	<script type="text/javascript" src="/resources/js/jquery-1.5.2.min.js"></script>
	{% block js %}{% endblock %}
	
	<title>Median Demosaic</title>
</head>
<body id="body">
	<div><img src={{url}}></div>
	<form action="http://127.0.0.1:7000/cgi-bin/demosaic_median.exe">
		<INPUT style="display:none" NAME="url" value={{url}} SIZE="10"><BR>
		<INPUT style="display:none" NAME="username" value={{username}}>
		<INPUT TYPE="SUBMIT" VALUE="Go!">
	</form>
</body>
</html>

web/templates/panorama.html
{% extends "foto_login.html" %}

{%block content%}
{%for id in ids%}
<h2>{{id}}</h2>
{%endfor%}
{%endblock%}

web/templates/panorama_list.html
{% extends "foto_login.html" %}


{% block title %}
	Photo List
{% endblock %}

{%block content%}
	<div class="content_div">
		<form action="/panorama_result/">
		<INPUT style="display:none" NAME="username" value={{username}}>
		<div class="ui-widget-header">
			<input class="btn" type="submit" value="Make Panorama"/>
		</div>
		<table>
			<tr>
				
				{% for photo in photos %}
					{% if forloop.counter0|divisibleby:"6" %}
						<tr style="padding:10px">
					{% endif %}
						<td>
							<input type="checkbox" name="id" value={{photo.id}}>
							<div>{{photo.title}}</div>
							<div><img class="imgs" src={{photo.url}}></div>
						</td>
				{% endfor %}
		</table>
		</form>
	</div>
{%endblock%}

web/templates/review.html
{% extends "base.html" %}
{% load i18n %}

{% block content_description %}
{{review.reviewer.username}}
{% endblock %}

{% block css%}
<link type="text/css" href="/resources/css/single_review.css" rel="stylesheet" />
{% endblock %}

{% block content %}
<div>
	<img style="width:120px;height:120px" src="/resources/img/profile.jpg"/>
	<h1>{{review.employer.name}}</h1>
	<h2>{{review.employer.company}}</h2>
	<h3>Worked <span id="color_text">{{review.get_position_type_display}}</span> their <span id="color_text">{{review.get_year_taken_display}}</span> year.</h3>
	<div id="prose">{{review.comment}}</div>
</div> 
<h3>Ranking and Review</h3>
<div>
	<div class="left_float right_pad">Overall:</div> 
	{% for i in overall %}
		<img class="left_float rating_img right_pad" src="/resources/img/overall_1.png" alt="overall"/>
	{% endfor %}
	</div>
	<div class="right_pad">
	<div class="left_float right_pad">Hours:</div> 
	{% for i in hours %}
		<img class="left_float rating_img right_pad" src="/resources/img/hours.jpg" alt="hours"/>
	{% endfor %}
	</div>
	<div class="right_pad">
	<div class="left_float right_pad">Pay:</div> 
	{% for i in pay %}
		<img class="left_float rating_img right_pad" src="/resources/img/dollar_1.png" alt="pay"/>
	{% endfor %}
	</div>
	<div class="right_pad">
	<div class="left_float right_pad">Difficulty:</div> 
	{% for i in difficulty %}
		<img class="left_float rating_img right_pad" src="/resources/img/difficulty.png" alt="difficulty"/>
	{% endfor %}
	</div>
</div>
<br><br><br>
<div class="left_float">
	<a class="nav_button_link" href="mailto:{{review.reviewer.email}}"><h3>Contact Reviewer</h3></a>
</div>
{% endblock %}

web/templates/review_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<table class="top_left" style="width:100%;height:100%">
		<tr class="top_left" style="width:100%;height:100%;">
			<td class="top_left" style="width:600px;height:100%;">
				<div style="width:100%;height:100%;">
					<div class="ui-widget-content">
						<p>Filter Search</p>
					</div>
					<div id="tabs" style="width:100%;height:100%">
						<ul>
							<li><a href="#tabs-1">Recommended</a></li>
							<li><a href="#tabs-2">Favorites</a></li>
							<li><a href="#tabs-3">Your Posts</a></li>
						</ul>
						<div id="tabs-1">
						{% if division_list%}									
							{% for division in division_list %}
								<h3><a href="#">{{division.name}} - {{division.company}}</a></h3>
								<ul>
								{% for review in division_reviews %}
									{% if review.employer.name == division.name and review.employer.company == division.company %}
										<li>Review by {{review.reviewer.username}}: {{review.employer.name}}-{{review.employer.company}}</li>
									{% endif %}
								{%endfor%}
								</ul>
							{% endfor %}
						{% else %}
							<p> Can't Load Accordion information <p>
						{% endif %}
						
						</div>
						<div id="tabs-2">
							<p>Contents 2</p>
						</div>
						<div id="tabs-3">	
							<p><button id="add_review">Add Review</button></p>
						</div>
					</div>
				</div>
			</td>
			<td style="position:absolute;top:0px;left:600px;width:100%;height:100%">
				<div class="ui-widget-content" style="width:100%;height:100%">
					<p>Content of detail container</p>
				</div>
			</td>
		</tr>
	</table>
{% endblock %}

web/templates/tonemap_bilateral.html
{% extends "foto_login.html" %}


{% block title %}
	Tonemap Bilateral
{% endblock %}

{%block content%}
	<div class="content_div">
	<div><img src={{url}}></div>
	<form action="http://127.0.0.1:7000/cgi-bin/tonemap_bilateral.exe">
		<input style="display:none" name="url" value={{url}} SIZE="10">
		<input style="display:none" name="username" value={{username}}>
		<p class="hel">Width</p>
		<input name="width" value="10">
		<p class="hel">Spatial Standard Deviation</p>
		<input name="d" value="8">
		<p class="hel">Range Standard Deviation</p>
		<input name="r" value="0.2">
		<p class="hel">Output Range</p>
		<input name="range" value="30"><br>
		<input type="submit" class="btn" value="Go!">
	</form>
	</div>
{%endblock%}

web/templates/tonemap_gaussian.html
{% extends "foto_login.html" %}


{% block title %}
	Tonemap Bilateral
{% endblock %}

{%block content%}
	<div class="content_div">
	<div><img src={{url}}></div>
	<form action="http://127.0.0.1:7000/cgi-bin/tonemap_gaussian.exe">
		<input style="display:none" name="url" value={{url}} SIZE="10"><BR>
		<input style="display:none" name="username" value={{username}}>
		<p class="hel">Filter Size</p>
		<input name="filter" value="21">
		<p class="hel">Standard Deviation</p>
		<input name="std" value="8">
		<p class="hel">Output Range</p>
		<input name="range" value="30"><br>
		<input type="submit" class="btn" value="Go!">
	</form>
	</div>
{%endblock%}